test workflow

diff --git a/.github/workflows/on-push.yml b/.github/workflows/on-push.yml
--- a/.github/workflows/on-push.yml
+++ b/.github/workflows/on-push.yml
@@ -47,119 +47,119 @@ jobs:
         path: Cargo.toml
 
 
-  cargo-build:
-    runs-on: ubuntu-latest
-    needs:
-    - release
-    steps:
+  # cargo-build:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #   - release
+  #   steps:
 
-    - uses: actions/checkout@v4
+  #   - uses: actions/checkout@v4
 
-    - name: Restore cargo cache
-      id: cache-cargo
-      uses: actions/cache/restore@v4
-      with:
-        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-        restore-keys: |
-          ${{ runner.os }}-cargo-
-        path: |
-          ~/.cargo/bin/
-          ~/.cargo/registry/index/
-          ~/.cargo/registry/cache/
-          ~/.cargo/git/db/
-          target/
+  #   - name: Restore cargo cache
+  #     id: cache-cargo
+  #     uses: actions/cache/restore@v4
+  #     with:
+  #       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+  #       restore-keys: |
+  #         ${{ runner.os }}-cargo-
+  #       path: |
+  #         ~/.cargo/bin/
+  #         ~/.cargo/registry/index/
+  #         ~/.cargo/registry/cache/
+  #         ~/.cargo/git/db/
+  #         target/
 
-    - uses: actions/download-artifact@v4
-      with:
-        name: Cargo.toml
+  #   - uses: actions/download-artifact@v4
+  #     with:
+  #       name: Cargo.toml
 
-    - run: git --no-pager diff --color
+  #   - run: git --no-pager diff --color
 
-    - name: Restore samples cache
-      id: cache-samples
-      uses: actions/cache@v4
-      with:
-       path: samples/content
-       key: cache-samples
+  #   - name: Restore samples cache
+  #     id: cache-samples
+  #     uses: actions/cache@v4
+  #     with:
+  #      path: samples/content
+  #      key: cache-samples
 
-    - if: steps.cache-samples.outputs.cache-hit != 'true'
-      run: ./samples/download-sample
+  #   - if: steps.cache-samples.outputs.cache-hit != 'true'
+  #     run: ./samples/download-sample
 
-    - run: |
-        curl "https://github.com/casey/intermodal/releases/download/v0.1.14/imdl-v0.1.14-x86_64-unknown-linux-musl.tar.gz" \
-          --location \
-          --show-error \
-          --silent \
-        | tar \
-          --extract \
-          --gzip \
-          --directory "/usr/local/bin" \
-          --file - \
-          "imdl"
+  #   - run: |
+  #       curl "https://github.com/casey/intermodal/releases/download/v0.1.14/imdl-v0.1.14-x86_64-unknown-linux-musl.tar.gz" \
+  #         --location \
+  #         --show-error \
+  #         --silent \
+  #       | tar \
+  #         --extract \
+  #         --gzip \
+  #         --directory "/usr/local/bin" \
+  #         --file - \
+  #         "imdl"
 
-    - run: sudo apt-get update
+  #   - run: sudo apt-get update
 
-    - run: sudo apt-get install flac lame sox imagemagick --yes
+  #   - run: sudo apt-get install flac lame sox imagemagick --yes
 
-    - run: cargo build --release
+  #   - run: cargo build --release
 
-    - name: Save cargo cache
-      id: cargo-cache-save
-      uses: actions/cache/save@v4
-      with:
-        key: ${{ steps.cache-cargo.outputs.cache-primary-key }}
-        path: |
-          ~/.cargo/bin/
-          ~/.cargo/registry/index/
-          ~/.cargo/registry/cache/
-          ~/.cargo/git/db/
-          target/
+  #   - name: Save cargo cache
+  #     id: cargo-cache-save
+  #     uses: actions/cache/save@v4
+  #     with:
+  #       key: ${{ steps.cache-cargo.outputs.cache-primary-key }}
+  #       path: |
+  #         ~/.cargo/bin/
+  #         ~/.cargo/registry/index/
+  #         ~/.cargo/registry/cache/
+  #         ~/.cargo/git/db/
+  #         target/
 
-    - run: rm -rf content
+  #   - run: rm -rf content
 
-    - run: ln -s samples/content content
+  #   - run: ln -s samples/content content
 
-    - run: |
-        tee config.yml <<EOF
-        announce_url: ${{ secrets.ANNOUNCE_URL }}
-        api_key: ${{ secrets.API_KEY }}
-        source: ${{ secrets.SOURCE }}
-        verbosity: trace
-        EOF
+  #   - run: |
+  #       tee config.yml <<EOF
+  #       announce_url: ${{ secrets.ANNOUNCE_URL }}
+  #       api_key: ${{ secrets.API_KEY }}
+  #       source: ${{ secrets.SOURCE }}
+  #       verbosity: trace
+  #       EOF
 
-    - run: touch output/cache.json
+  #   - run: touch output/cache.json
 
-    - run: touch output/queue.yml
+  #   - run: touch output/queue.yml
 
-    - run: cargo test --release --no-fail-fast
+  #   - run: cargo test --release --no-fail-fast
 
-    - name: Run cargo check
-      run: |
-        if ! cargo check --quiet --all-targets --message-format short
-        then
-          echo "::warning title=Cargo Check Failed::Please review the output for details."
-        fi
+  #   - name: Run cargo check
+  #     run: |
+  #       if ! cargo check --quiet --all-targets --message-format short
+  #       then
+  #         echo "::warning title=Cargo Check Failed::Please review the output for details."
+  #       fi
 
-    - name: Run cargo clippy
-      run: |
-        if ! cargo clippy --quiet --all-targets --message-format short
-        then
-          echo "::warning title=Clippy Check Failed::Please review the output for details."
-        fi
+  #   - name: Run cargo clippy
+  #     run: |
+  #       if ! cargo clippy --quiet --all-targets --message-format short
+  #       then
+  #         echo "::warning title=Clippy Check Failed::Please review the output for details."
+  #       fi
 
-    - name: Run cargo fmt
-      run: |
-        if ! cargo fmt --check
-        then
-          echo "::warning title=Format Check Failed::Please review the output for details."
-        fi
+  #   - name: Run cargo fmt
+  #     run: |
+  #       if ! cargo fmt --check
+  #       then
+  #         echo "::warning title=Format Check Failed::Please review the output for details."
+  #       fi
 
-    - run: git --no-pager diff --color
+  #   - run: git --no-pager diff --color
 
-    - uses: actions/upload-artifact@v4
-      with:
-        name: caesura
-        path: target/release/caesura
+  #   - uses: actions/upload-artifact@v4
+  #     with:
+  #       name: caesura
+  #       path: target/release/caesura
 
 
   # cargo-publish:
@@ -237,7 +237,7 @@ jobs:
 
   docker-build:
     runs-on: ubuntu-latest
-    if: ${{ needs.release.outputs.version != ''}}
+    # if: ${{ needs.release.outputs.version != ''}}
     needs:
     - release
     steps:
